apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: webapp
    tier: backend
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32000