apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: webapp
    app.kubernetes.io/component: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30002
  type: NodePort
