apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
      component: backend
  template:
    metadata:
      labels:
        app: webapp
        component: backend
        app.kubernetes.io/component: frontend
        app.kubernetes.io/component: backend
    spec:
      containers:
      - name: frontend
        image: client:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: API_URL
          value: "http://backend-service:3000"

      - name: backend
        imagePullPolicy: Never
        image: server:latest
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          value: "10.105.95.152"
        - name: DB_PORT
          value: "3306"
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          value: "root"
        - name: DB_NAME
          value: "projetkub"